config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :carts
      resources :items
      resources :line_items
      resources :orders
      root "users#index"
  end
  root 'items#index'
  resources :items, only: [:index, :show]
  resources :line_items
  resources :carts
  devise_for :users
  resources :charges
  resources :users, only: [:show, :edit, :update]
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event

  validates :stripe_customer_id, uniqueness: true

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user

  def add_item(item)
    current_item = line_items.find_by(item_id: item.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(item_id: item.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  
  validate :start_date_cannot_be_in_the_past

  validates :start_date, presence: true 
   
  validates :duration, presence: true
  
  validates :description, presence: true, length: { in: 20..1000, message: "description need 20 car. min and 1000 car. max"} 
  
  validates :title, presence: true, length: { in: 5..140, message: "title need 5 car. min and 140 car. max"} 
  
  validates :price, presence: true, numericality: { in: 1..1000, }
  
  validates :location, presence: true

private

  def start_date_cannot_be_in_the_past
    if start_date < Time.now
      errors.add(:start_date, 'No past date')
    end
  end

end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders

  validates :title, presence: true, length: { in: 2..30 }
  validates :description, presence: true, length: { in: 10..1000 }
  validates :price, presence: true, length: { in: 0..1000 }
  validates :image_url, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price.to_i * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  has_one :cart
  has_many :orders
  has_many :items, through: :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_send
      UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new(title: "", content: "", user: User.last)
  end

  def create
    @gossip = Gossip.new(title: params[:title],
      content: params[:content],
      user: User.find(params[:user]))
      if @gossip.save
        flash[:success] = "Merci pour ton potin !"
        redirect_to root_path
      else
        render 'new'
      end
  end

  def edit
  end

  def update
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_author(cart)
    user_signed_in? && current_user.id == cart.user_id
  end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<div class="container">

<% the_id = params['id'] %>
<h1 class="py-3">Edite le potin</h1>
<br>

<p class="text-left">le potin de <%= link_to Gossip.find(the_id.to_i).user.first_name, user_path(Gossip.find(the_id.to_i).user.id)%> est édité.</p>


<div class="form-group p-5 border rounded">
 <%= form_tag url_for(action: 'update'), method: "post" do %>

    <%= label_tag 'Title', nil, :class => "" %>
    <%= text_field_tag 'title', nil, value: Gossip.find(the_id.to_i).title, :class => "form-control" %>
    <br /> <br />

    <%= label_tag 'Content', nil, :class => "" %>
    <%= text_field_tag 'content', nil, value: Gossip.find(the_id.to_i).content, :class => "form-control"  %>
    <br /> <br />

    <%= submit_tag "valider", :class => "btn btn-primary btn-lg" %>

  <% end %>
   <br /> <br />
<a href="destroy" class="btn btn-danger btn-sm">Supprime ce potin</a>
</div>
<a href="/">Retourne à la page des potins</a>
</div>

app/views/gossips/index.html.erb
<% Gossip.all.each do |gossip| %>
  <div class="card">
    <div class="card-content">
      <p class="title">
        <%= gossip.title %>
      </p>
      <p class="subtitle">
        <%= gossip.user.full_name %>
      </p>
    </div>
    <footer class="card-footer">
      <a class="card-footer-item" href="<%= gossip_path(gossip.id)%>">
        <span>
          Lire le potin
        </span>
      </a>
      <a class="card-footer-item" href="<%= new_user_path %>">
        <span>
          Découvrir l'auteur
        </span>
      </a>
    </footer>
  </div>
<% end %>

app/views/gossips/new.html.erb
<h1>Gossips#new</h1>
<p>Find me in app/views/gossips/new.html.erb</p>
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Title' %>
  <%= text_field_tag 'title', @post.title %>
  <br /> <br />

  <%= label_tag 'Body' %>
  <%= text_area_tag 'body', @post.body %>
  <br /> <br />

  <%= label_tag 'Author' %>
  <%= text_field_tag 'author', @post.author %>
  <br /> <br />

  <%= submit_tag "Create Post" %>

  <% end %>



    <h1 class="py-3">#BalanceTonPotin</h1>
  <p class="py-3">Balance ton potin via le formulaire ci-dessous 👇</p>
  <form action='/' method='GET' class="form-group p-5 border rounded">
    Quel est ton nom ?  <input type='text' name='gossip_author' class="form-control" placeholder="Quel nom?" /><br/>
    Quel est ton potin ? <input type='text' name='gossip_content' class="form-control" placeholder="Veuillez saisir votre potin svp!" /><br/>
    <input type='submit' class="btn btn-primary w-100" s/>
  </form>
  <a href="/">Retourne à la page des potins</a>

app/views/gossips/show.html.erb
<div class="container py-3 text-center">
  
  <h1>Votre PAGE POTIN</h1>
  <br>

  <div class="card py-3">
    <h2 class="card-title">Voici la page du potin n°<%= the_id = params['id'] %></h2>
   
    <div class="card-body text-left">

      <div class="card-text">
        <p><strong>Son auteur : </strong><%= @gossip.user.first_name %></p>

        <p><strong>Le contenu du potin : </strong><%= @gossip.content %></p>
        <br>

      </div>

      <a href="<%=the_id%>/edit" class="btn btn-primary btn-sm">Edite le potin</a>

    </div>
  </div>

  <br>
  <a href="/">Retourne à la page des potins</a>

</div>