config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :carts
      resources :items
      resources :line_items
      resources :orders
      root "users#index"
  end
  root 'items#index'
  resources :items, only: [:index, :show]
  resources :line_items
  resources :carts
  devise_for :users
  resources :charges
  resources :users, only: [:show, :edit, :update]
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event

  validates :stripe_customer_id, uniqueness: true

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user

  def add_item(item)
    current_item = line_items.find_by(item_id: item.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(item_id: item.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  
  validate :start_date_cannot_be_in_the_past

  validates :start_date, presence: true 
   
  validates :duration, presence: true
  
  validates :description, presence: true, length: { in: 20..1000, message: "description need 20 car. min and 1000 car. max"} 
  
  validates :title, presence: true, length: { in: 5..140, message: "title need 5 car. min and 140 car. max"} 
  
  validates :price, presence: true, numericality: { in: 1..1000, }
  
  validates :location, presence: true

private

  def start_date_cannot_be_in_the_past
    if start_date < Time.now
      errors.add(:start_date, 'No past date')
    end
  end

end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders

  validates :title, presence: true, length: { in: 2..30 }
  validates :description, presence: true, length: { in: 10..1000 }
  validates :price, presence: true, length: { in: 0..1000 }
  validates :image_url, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def total_price
    item.price.to_i * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send

  has_one :cart
  has_many :orders
  has_many :items, through: :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def welcome_send
      UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_author(cart)
    user_signed_in? && current_user.id == cart.user_id
  end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="p-4">
  <div class="grid md:grid-cols-3 sm:grid-cols-1 lg:grid-cols-4">

<% @items.each do |item| %>

<div class="flex justify-center items-center mb-2">
  <style>
    button {
    background-color: #667eea;
    box-shadow: 0 0 0 0 #ec008c, 0.2rem 0.2rem 10px #5B607A;
    }
    button:hover {
    box-shadow: 0 0 0 0 #ec008c, 0.2rem 0.2rem 20px #5B607A;
    }
  </style>
  <div class="container mx-auto max-w-xs rounded-lg overflow-hidden shadow-lg bg-indigo-500">
    <div class="relative">
      <a href="<%= item_path(item) %>">
        <img class="w-full" src="<%= item.image_url %>" alt="<%= item.title %>">
        <% if user_signed_in? %>
          <div class="text-right tracking-wide absolute w-full -mt-12 -ml-3">
            <button class="p-1 rounded-full transition ease-in duration-200 focus:outline-none">
              <a title="Ajouter au panier" href="<%= user_path(current_user) %>">
              <svg viewBox="0 0 20 20" enable-background="new 0 0 20 20" class="w-8 h-8">
                <path fill="#FFFFFF" d="M16,10c0,0.553-0.048,1-0.601,1H11v4.399C11,15.951,10.553,16,10,16c-0.553,0-1-0.049-1-0.601V11H4.601
                    C4.049,11,4,10.553,4,10c0-0.553,0.049-1,0.601-1H9V4.601C9,4.048,9.447,4,10,4c0.553,0,1,0.048,1,0.601V9h4.399
                    C15.952,9,16,9.447,16,10z" />
              </svg>
              </a>
            </button>
          </div>
        <% else %>
          <div class="text-right tracking-wide absolute w-full -mt-12 -ml-3"> </div>
        <% end %>
      </a>
    </div>
    <div class="py-2 px-4 text-center tracking-wide">
      <p class="text-white tracking-wide uppercase text-lg font-bold"><%= item.title %></p>
    </div>
  </div>
</div>

<% end %>

  </div>
</div>

app/views/items/show.html.erb
<section class="text-white body-font overflow-hidden">
  <div class="container px-5 py-5 mx-auto">
    <div class="lg:w-4/5 bg-indigo-500 rounded p-5 mx-auto flex flex-wrap">
      <img class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="<%= @item.image_url %>">
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h1 class="text-white text-3xl title-font uppercase font-medium mb-1"><%= @item.title %></h1>
        <p class="leading-relaxed"><%= @item.description %></p>
        <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
          <div class="flex ml-6 items-center">
            <div class="relative">
              <span class="absolute right-0 top-0 h-full w-10 text-center text-gray-600 pointer-events-none flex items-center justify-center">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4" viewBox="0 0 24 24">
                  <path d="M6 9l6 6 6-6"></path>
                </svg>
              </span>
            </div>
          </div>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl"><%= @item.price %>€</span>
          <% if user_signed_in? %>
            <%= link_to "Ajouter au panier", user_path(current_user), class: "flex ml-auto text-indigo-500 bg-white border-0 py-2 px-6 focus:outline-none hover:text-indigo-900 rounded" %>
          <% else %>
            <%= link_to "Se connecter", new_user_session_path, class: "flex ml-auto text-white border border-white py-2 px-6 focus:outline-none hover:bg-white hover:text-indigo-500 rounded" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>